/**
 * Built-in templates from spec §11.
 * Each is loaded into the templates table on first run; users can fork or disable.
 */
import type { Template } from '../types/entities';

export type BuiltinTemplate = Omit<Template, 'id' | 'created_at' | 'updated_at'>;

export const BUILTIN_TEMPLATES: BuiltinTemplate[] = [
  {
    name: 'General Meeting',
    description: 'Default for any meeting.',
    when_to_use: 'Default fallback when no other template matches.',
    required_sections: ['Summary', 'Key discussion points', 'Decisions', 'Action items', 'Open questions'],
    optional_sections: ['Risks/blockers', 'Important quotes', 'Follow-up email', 'Personal reminders'],
    formatting_rules: 'Bullets. Concise. Direct.',
    action_item_format: '- [ ] <task> — <owner> (<due>)',
    follow_up_style: 'Brief recap with action items.',
    auto_apply_rules: [],
    builtin: true,
  },
  {
    name: '1:1',
    description: 'Recurring 1:1 with a colleague, mentor, or manager.',
    when_to_use: 'Recurring 1:1 meetings.',
    required_sections: ['Updates', 'Wins', 'Blockers', 'Discussion', 'Action items'],
    optional_sections: ['Career', 'Feedback', 'Personal'],
    formatting_rules: 'Personal, supportive tone. Carry items forward across sessions.',
    action_item_format: '- [ ] <task> — <owner>',
    follow_up_style: 'Short personal recap.',
    auto_apply_rules: [
      { field: 'recurring', operator: 'is_true', value: true },
    ],
    builtin: true,
  },
  {
    name: 'Customer Discovery',
    description: 'Customer interviews — pain, jobs to be done, willingness to pay.',
    when_to_use: 'Sales discovery, customer research, user interviews.',
    required_sections: ['Customer context', 'Pain points', 'Jobs to be done', 'Current solution', 'Willingness to pay', 'Action items'],
    optional_sections: ['Quotes', 'Competitive context', 'Use cases', 'Buying signals'],
    formatting_rules: 'Quote the customer. Capture exact pain language.',
    action_item_format: '- [ ] <task> — <owner> (<due>)',
    follow_up_style: 'Thank-you with summary of next steps.',
    drive_folder_path: '/AI Meeting Notes/Companies/{company}',
    auto_apply_rules: [],
    builtin: true,
  },
  {
    name: 'Sales Call',
    description: 'Sales meeting with a prospect.',
    when_to_use: 'Active sales conversations.',
    required_sections: ['Stakeholders', 'Pain', 'Use case fit', 'Objections', 'Next steps', 'Action items'],
    optional_sections: ['Pricing notes', 'Competitive context'],
    formatting_rules: 'Concrete next steps, owners, and dates.',
    action_item_format: '- [ ] <task> — <owner> (<due>)',
    follow_up_style: 'Sales follow-up with proposed next step.',
    auto_apply_rules: [],
    builtin: true,
  },
  {
    name: 'Investor Meeting',
    description: 'Investor pitch or update.',
    when_to_use: 'Calls with investors or potential investors.',
    required_sections: ['Investor context', 'Their interests', 'Their objections', 'Asks', 'Commitments', 'Action items'],
    optional_sections: ['Quotes', 'Intro requests'],
    formatting_rules: 'Crisp. Track every commitment.',
    action_item_format: '- [ ] <task> — <owner> (<due>)',
    follow_up_style: 'Investor follow-up with next milestone.',
    drive_folder_path: '/AI Meeting Notes/Projects/Investor Calls',
    auto_apply_rules: [
      { field: 'calendar_title', operator: 'contains', value: 'investor' },
    ],
    builtin: true,
  },
  {
    name: 'Recruiting Interview',
    description: 'Candidate interview.',
    when_to_use: 'Interviewing a candidate.',
    required_sections: ['Candidate', 'Strengths', 'Concerns', 'Signals', 'Recommendation', 'Action items'],
    optional_sections: ['Quotes', 'Coding/portfolio notes'],
    formatting_rules: 'Evidence-based. Note exact quotes.',
    action_item_format: '- [ ] <task> — <owner>',
    follow_up_style: 'Internal debrief and candidate follow-up.',
    auto_apply_rules: [],
    builtin: true,
  },
  {
    name: 'Research Interview',
    description: 'Research interview / user study.',
    when_to_use: 'User research sessions.',
    required_sections: ['Participant context', 'Tasks observed', 'Pain points', 'Quotes', 'Themes', 'Action items'],
    optional_sections: ['Hypotheses tested', 'Open questions'],
    formatting_rules: 'Verbatim quotes when available.',
    action_item_format: '- [ ] <task>',
    follow_up_style: 'Thank-you with incentive details.',
    auto_apply_rules: [],
    builtin: true,
  },
  {
    name: 'Product Feedback',
    description: 'User feedback on the product.',
    when_to_use: 'Product feedback sessions.',
    required_sections: ['Feedback', 'Bugs', 'Feature requests', 'Customer pain', 'Action items'],
    optional_sections: ['Quotes'],
    formatting_rules: 'Bucket by bugs vs features vs UX.',
    action_item_format: '- [ ] <task> — <owner>',
    follow_up_style: 'Acknowledge feedback, share roadmap items.',
    auto_apply_rules: [],
    builtin: true,
  },
  {
    name: 'Engineering Sync',
    description: 'Internal engineering meeting.',
    when_to_use: 'Engineering syncs and standups.',
    required_sections: ['Status', 'Blockers', 'Decisions', 'Action items'],
    optional_sections: ['Risks', 'Architecture notes'],
    formatting_rules: 'Technical, terse.',
    action_item_format: '- [ ] <task> — <owner> (<due>)',
    follow_up_style: 'Recap blockers and decisions.',
    auto_apply_rules: [],
    builtin: true,
  },
  {
    name: 'Design Review',
    description: 'Design critique / review.',
    when_to_use: 'Design reviews.',
    required_sections: ['Design under review', 'Feedback', 'Decisions', 'Open questions', 'Action items'],
    optional_sections: ['Screenshots/links'],
    formatting_rules: 'Track open vs decided.',
    action_item_format: '- [ ] <task> — <owner>',
    follow_up_style: 'Share decisions and follow-ups with team.',
    auto_apply_rules: [],
    builtin: true,
  },
  {
    name: 'Class Lecture',
    description: 'Class or lecture notes.',
    when_to_use: 'Classes and lectures.',
    required_sections: ['Topic', 'Key concepts', 'Examples', 'Open questions'],
    optional_sections: ['Reading list', 'Assignments'],
    formatting_rules: 'Outline-style notes with definitions.',
    action_item_format: '- [ ] <task>',
    follow_up_style: 'Summary for personal review.',
    auto_apply_rules: [],
    builtin: true,
  },
  {
    name: 'Office Hours',
    description: 'Office hours with a professor or mentor.',
    when_to_use: 'Office hours meetings.',
    required_sections: ['Question', 'Discussion', 'Resolution', 'Follow-ups'],
    optional_sections: ['Resources mentioned'],
    formatting_rules: 'Question/answer style.',
    action_item_format: '- [ ] <task>',
    follow_up_style: 'Thank-you and recap.',
    auto_apply_rules: [
      { field: 'calendar_title', operator: 'contains', value: 'office hours' },
    ],
    builtin: true,
  },
  {
    name: 'Advisor Meeting',
    description: 'Advisor / mentor call.',
    when_to_use: 'Mentor and advisor conversations.',
    required_sections: ['Topics', 'Advice', 'Commitments', 'Action items'],
    optional_sections: ['Asks', 'Intros'],
    formatting_rules: 'Capture advice verbatim.',
    action_item_format: '- [ ] <task>',
    follow_up_style: 'Thank-you and recap.',
    auto_apply_rules: [],
    builtin: true,
  },
  {
    name: 'Startup Mentor Call',
    description: 'Startup mentorship call.',
    when_to_use: 'Mentor calls about your startup.',
    required_sections: ['Topics', 'Mentor advice', 'Open questions', 'Action items'],
    optional_sections: ['Asks', 'Intros'],
    formatting_rules: 'Direct quotes preferred.',
    action_item_format: '- [ ] <task>',
    follow_up_style: 'Mentor recap and next ask.',
    auto_apply_rules: [],
    builtin: true,
  },
  {
    name: 'Project Check-in',
    description: 'Project progress meeting.',
    when_to_use: 'Project check-ins and standups.',
    required_sections: ['Progress', 'Risks', 'Decisions', 'Action items'],
    optional_sections: ['Schedule', 'Budget'],
    formatting_rules: 'Status-style.',
    action_item_format: '- [ ] <task> — <owner> (<due>)',
    follow_up_style: 'Progress recap.',
    auto_apply_rules: [],
    builtin: true,
  },
  {
    name: 'Doctor / Research Meeting',
    description: 'Medical / research consultation.',
    when_to_use: 'Doctor visits or research consultations.',
    required_sections: ['Reason for meeting', 'Findings', 'Recommendations', 'Follow-ups'],
    optional_sections: ['Personal notes'],
    formatting_rules: 'Plain language, careful.',
    action_item_format: '- [ ] <task>',
    follow_up_style: 'Personal recap only.',
    auto_apply_rules: [],
    builtin: true,
  },
];
