/**
 * Renders a meeting + generated note + transcript chunks to a markdown
 * document matching spec §12 ("Google Doc format").
 *
 * Layout (top to bottom):
 *   # Title
 *   Date / time line
 *   App / Attendees / Description
 *   ## Summary
 *   ## Decisions
 *   ## Action Items   (with owner, due, priority)
 *   ## Open Questions
 *   ## Key Quotes
 *   ## Raw Notes
 *   ## Transcript
 *   ---
 *   Metadata (small print)
 */

import type {
  Meeting,
  GeneratedNote,
  TranscriptChunk,
  Person,
} from '@shared/types/entities';

export interface MarkdownContext {
  meeting: Meeting;
  note?: GeneratedNote | null;
  chunks?: TranscriptChunk[];
  attendees?: Person[]; // resolved person rows (not just ids)
  description?: string;
}

export function renderMeetingMarkdown(ctx: MarkdownContext): string {
  const { meeting, note, chunks = [], attendees = [], description } = ctx;
  const lines: string[] = [];

  lines.push(`# ${escapeMd(meeting.title || 'Untitled Meeting')}`);
  lines.push('');

  const startedAt = new Date(meeting.started_at);
  const endedAt = meeting.ended_at ? new Date(meeting.ended_at) : null;
  lines.push(`**Date:** ${formatDate(startedAt)}  `);
  lines.push(`**Time:** ${formatTime(startedAt)}${endedAt ? `–${formatTime(endedAt)} (${duration(startedAt, endedAt)})` : ''}  `);
  lines.push(`**App:** ${prettyApp(meeting.source_app)}  `);
  if (attendees.length) {
    lines.push(`**Attendees:** ${attendees.map(formatAttendee).join(', ')}  `);
  }
  if (description && description.trim()) {
    lines.push('');
    lines.push(`**Description:** ${escapeMd(description.trim())}`);
  }
  lines.push('');

  if (note?.summary) {
    lines.push('## Summary');
    lines.push('');
    lines.push(note.summary.trim());
    lines.push('');
  }

  // Custom sections (template-driven) come right after summary.
  for (const sec of note?.sections ?? []) {
    if (!sec.body?.trim()) continue;
    lines.push(`## ${escapeMd(sec.heading)}`);
    lines.push('');
    lines.push(sec.body.trim());
    lines.push('');
  }

  if (note?.decisions?.length) {
    lines.push('## Decisions');
    lines.push('');
    for (const d of note.decisions) lines.push(`- ${escapeMd(d.text)}`);
    lines.push('');
  }

  if (note?.action_items?.length) {
    lines.push('## Action Items');
    lines.push('');
    for (const a of note.action_items) {
      const meta: string[] = [];
      if (a.owner) meta.push(`owner: ${a.owner}`);
      if (a.due_date) meta.push(`due: ${a.due_date.slice(0, 10)}`);
      if (a.priority) meta.push(`priority: ${a.priority}`);
      const tail = meta.length ? ` _(${meta.join(', ')})_` : '';
      lines.push(`- [ ] ${escapeMd(a.task)}${tail}`);
    }
    lines.push('');
  }

  if (note?.open_questions?.length) {
    lines.push('## Open Questions');
    lines.push('');
    for (const q of note.open_questions) lines.push(`- ${escapeMd(q)}`);
    lines.push('');
  }

  if (note?.risks?.length) {
    lines.push('## Risks');
    lines.push('');
    for (const r of note.risks) lines.push(`- ${escapeMd(r)}`);
    lines.push('');
  }

  if (note?.quotes?.length) {
    lines.push('## Key Quotes');
    lines.push('');
    for (const q of note.quotes) {
      lines.push(`> "${escapeMd(q.text)}" — ${escapeMd(q.speaker)}${q.start_time != null ? ` _(at ${formatSeconds(q.start_time)})_` : ''}`);
      lines.push('');
    }
  }

  if (meeting.raw_notes && meeting.raw_notes.trim()) {
    lines.push('## Raw Notes');
    lines.push('');
    lines.push(meeting.raw_notes.trim());
    lines.push('');
  }

  if (chunks.length) {
    lines.push('## Transcript');
    lines.push('');
    let lastSpeaker = '';
    for (const c of chunks) {
      if (!c.is_final || c.is_deleted) continue;
      const speaker = c.speaker_name || c.speaker_id || 'Speaker';
      const ts = `[${formatSeconds(c.start_time)}]`;
      if (speaker !== lastSpeaker) {
        if (lastSpeaker) lines.push('');
        lines.push(`**${escapeMd(speaker)}** ${ts}`);
        lastSpeaker = speaker;
      } else {
        lines.push(`${ts}`);
      }
      lines.push(c.text.trim());
    }
    lines.push('');
  }

  // Metadata footer
  lines.push('---');
  lines.push('');
  lines.push(`<sub>Generated by Cherios · meeting id: \`${meeting.id}\` · ${note?.model ? `model: ${note.model} · ` : ''}exported ${new Date().toISOString()}</sub>`);

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function escapeMd(s: string): string {
  // Conservative — we only escape the characters that would actually
  // change rendering at line start. Inline _, *, ` etc. are fine to leave;
  // users may want them.
  return s.replace(/\r/g, '');
}

function formatDate(d: Date): string {
  return d.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
}
function formatTime(d: Date): string {
  return d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
}
function duration(a: Date, b: Date): string {
  const mins = Math.max(0, Math.round((b.getTime() - a.getTime()) / 60000));
  if (mins < 60) return `${mins}m`;
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return m ? `${h}h ${m}m` : `${h}h`;
}
function formatSeconds(s: number): string {
  const m = Math.floor(s / 60);
  const sec = Math.floor(s % 60);
  return `${m.toString().padStart(2, '0')}:${sec.toString().padStart(2, '0')}`;
}
function formatAttendee(p: Person): string {
  if (p.email) return `${p.name} <${p.email}>`;
  return p.name;
}
function prettyApp(a: Meeting['source_app']): string {
  return ({
    zoom: 'Zoom',
    google_meet: 'Google Meet',
    microsoft_teams: 'Microsoft Teams',
    slack_huddle: 'Slack Huddle',
    webex: 'Webex',
    discord: 'Discord',
    facetime: 'FaceTime',
    browser: 'Browser',
    unknown: 'Unknown',
  } as const)[a] ?? a;
}
